### ISSUE TITLE
Uncaught exception in testrunner lead to partial results

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#41386]
c.f. the missing results in https://wpt.fyi/results/?q=status%3Amissing&run_id=6282678108684288&run_id=5163365977030656&run_id=5090383543926784

from https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=104439&view=logs&j=00001f08-a2aa-53ea-0d73-1e32cf609b1b&t=f70068c5-45e1-5c45-a22f-d474b9a4901e (but copied here before it expires):

```
2023-07-17T04:26:21.5240850Z 34:14.15 TEST_START: /css/selectors/media/media-playback-state.html
2023-07-17T04:26:46.5549760Z 34:39.19 INFO Got timeout in harness
2023-07-17T04:26:46.5556810Z 34:39.19 TEST_END: TIMEOUT, expected OK - TestRunner hit external timeout (this may indicate a hang)
2023-07-17T04:27:06.8822010Z 34:39.20 WARNING Traceback (most recent call last):
2023-07-17T04:27:06.8824050Z   File "/Users/runner/work/1/s/tools/wptrunner/wptrunner/executors/base.py", line 302, in run_test
2023-07-17T04:27:06.8825930Z     result = self.do_test(test)
2023-07-17T04:27:06.8827660Z              ^^^^^^^^^^^^^^^^^^
2023-07-17T04:27:06.8829350Z   File "/Users/runner/work/1/s/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 544, in do_test
2023-07-17T04:27:06.8830690Z     self.extra_timeout).run()
2023-07-17T04:27:06.8832350Z                         ^^^^^
2023-07-17T04:27:06.8833810Z   File "/Users/runner/work/1/s/tools/wptrunner/wptrunner/executors/base.py", line 206, in run
2023-07-17T04:27:06.8835720Z     if self.protocol.is_alive():
2023-07-17T04:27:06.8837440Z        ^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-17T04:27:06.8839260Z   File "/Users/runner/work/1/s/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 467, in is_alive
2023-07-17T04:27:06.8840980Z     self.webdriver.send_session_command("GET", "window", timeout=2)
2023-07-17T04:27:06.8842910Z   File "/Users/runner/work/1/s/tools/webdriver/webdriver/client.py", line 658, in send_session_command
2023-07-17T04:27:06.8844270Z     return self.send_command(method, url, body, timeout)
2023-07-17T04:27:06.8845820Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-17T04:27:06.8847540Z   File "/Users/runner/work/1/s/tools/webdriver/webdriver/client.py", line 610, in send_command
2023-07-17T04:27:06.8849590Z     response = self.transport.send(
2023-07-17T04:27:06.8856880Z                ^^^^^^^^^^^^^^^^^^^^
2023-07-17T04:27:06.8860550Z   File "/Users/runner/work/1/s/tools/webdriver/webdriver/transport.py", line 234, in send
2023-07-17T04:27:06.8862030Z     response = self._request(method, uri, payload, headers, timeout=None)
2023-07-17T04:27:06.8863330Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-17T04:27:06.8864630Z   File "/Users/runner/work/1/s/tools/webdriver/webdriver/transport.py", line 259, in _request
2023-07-17T04:27:06.8865610Z     response = self.connection.getresponse()
2023-07-17T04:27:06.8865930Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-17T04:27:06.8867110Z   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1378, in getresponse
2023-07-17T04:27:06.8868240Z     response.begin()
2023-07-17T04:27:06.8869530Z   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 318, in begin
2023-07-17T04:27:06.8870310Z     version, status, reason = self._read_status()
2023-07-17T04:27:06.8870570Z                               ^^^^^^^^^^^^^^^^^^^
2023-07-17T04:27:06.8870890Z   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 287, in _read_status
2023-07-17T04:27:06.8872560Z     raise RemoteDisconnected("Remote end closed connection without"
2023-07-17T04:27:06.8873370Z http.client.RemoteDisconnected: Remote end closed connection without response
2023-07-17T04:27:06.8873580Z 
2023-07-17T04:27:06.8874340Z 34:59.51 WARNING Command left in command_queue during cleanup: 'test_ended', (<wptrunner.wpttest.TestharnessTest /css/selectors/media/media-playback-state.html>, (<wptrunner.wpttest.TestharnessResult INTERNAL-ERROR>, []))
2023-07-17T04:27:06.8876620Z 34:39.20 INFO Closing logging queue
2023-07-17T04:27:06.8878610Z 34:39.20 INFO queue closed
2023-07-17T04:27:06.9608870Z 34:59.59 ERROR Traceback (most recent call last):
2023-07-17T04:27:06.9610950Z   File "/Users/runner/work/1/s/_venv3/lib/python3.11/site-packages/psutil/_psposix.py", line 121, in wait_pid
2023-07-17T04:27:06.9611660Z     retpid, status = os.waitpid(pid, flags)
2023-07-17T04:27:06.9611930Z                      ^^^^^^^^^^^^^^^^^^^^^^
2023-07-17T04:27:06.9612180Z ChildProcessError: [Errno 10] No child processes
2023-07-17T04:27:06.9612320Z 
2023-07-17T04:27:06.9612570Z During handling of the above exception, another exception occurred:
2023-07-17T04:27:06.9612750Z 
2023-07-17T04:27:06.9614060Z Traceback (most recent call last):
2023-07-17T04:27:06.9616020Z   File "/Users/runner/work/1/s/tools/wptrunner/wptrunner/browsers/safari.py", line 209, in stop
2023-07-17T04:27:06.9617650Z     proc.wait(10)
2023-07-17T04:27:06.9620020Z   File "/Users/runner/work/1/s/_venv3/lib/python3.11/site-packages/psutil/__init__.py", line 1270, in wait
2023-07-17T04:27:06.9621260Z     self._exitcode = self._proc.wait(timeout)
2023-07-17T04:27:06.9622930Z                      ^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-17T04:27:06.9626090Z   File "/Users/runner/work/1/s/_venv3/lib/python3.11/site-packages/psutil/_psosx.py", line 346, in wrapper
2023-07-17T04:27:06.9626990Z     return fun(self, *args, **kwargs)
2023-07-17T04:27:06.9627930Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-17T04:27:06.9629610Z   File "/Users/runner/work/1/s/_venv3/lib/python3.11/site-packages/psutil/_psosx.py", line 520, in wait
2023-07-17T04:27:06.9631250Z     return _psposix.wait_pid(self.pid, timeout, self._name)
2023-07-17T04:27:06.9632600Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-17T04:27:06.9634370Z   File "/Users/runner/work/1/s/_venv3/lib/python3.11/site-packages/psutil/_psposix.py", line 132, in wait_pid
2023-07-17T04:27:06.9635940Z     interval = sleep(interval)
2023-07-17T04:27:06.9637410Z                ^^^^^^^^^^^^^^^
2023-07-17T04:27:06.9639520Z   File "/Users/runner/work/1/s/_venv3/lib/python3.11/site-packages/psutil/_psposix.py", line 114, in sleep
2023-07-17T04:27:06.9640650Z     raise TimeoutExpired(timeout, pid=pid, name=proc_name)
2023-07-17T04:27:06.9642440Z psutil.TimeoutExpired: timeout after 10 seconds (pid=12596)
2023-07-17T04:27:06.9643870Z 
2023-07-17T04:27:06.9644810Z During handling of the above exception, another exception occurred:
2023-07-17T04:27:06.9645530Z 
2023-07-17T04:27:06.9646030Z Traceback (most recent call last):
2023-07-17T04:27:06.9647320Z   File "/Users/runner/work/1/s/_venv3/lib/python3.11/site-packages/psutil/_psposix.py", line 121, in wait_pid
2023-07-17T04:27:06.9648420Z     retpid, status = os.waitpid(pid, flags)
2023-07-17T04:27:06.9649170Z                      ^^^^^^^^^^^^^^^^^^^^^^
2023-07-17T04:27:06.9649870Z ChildProcessError: [Errno 10] No child processes
2023-07-17T04:27:06.9650340Z 
2023-07-17T04:27:06.9650640Z During handling of the above exception, another exception occurred:
2023-07-17T04:27:06.9651110Z 
2023-07-17T04:27:06.9651550Z Traceback (most recent call last):
2023-07-17T04:27:06.9652420Z   File "/Users/runner/work/1/s/tools/wptrunner/wptrunner/testrunner.py", line 381, in run
2023-07-17T04:27:06.9653080Z     new_state = f()
2023-07-17T04:27:06.9653310Z                 ^^^
2023-07-17T04:27:06.9654170Z   File "/Users/runner/work/1/s/tools/wptrunner/wptrunner/testrunner.py", line 788, in restart_runner
2023-07-17T04:27:06.9655540Z     self.stop_runner(force=self.state.force_stop)
2023-07-17T04:27:06.9656480Z   File "/Users/runner/work/1/s/tools/wptrunner/wptrunner/testrunner.py", line 809, in stop_runner
2023-07-17T04:27:06.9657450Z     self.browser.stop(force=force)
2023-07-17T04:27:06.9658430Z   File "/Users/runner/work/1/s/tools/wptrunner/wptrunner/testrunner.py", line 240, in stop
2023-07-17T04:27:06.9659200Z     self.browser.stop(force=force)
2023-07-17T04:27:06.9659870Z   File "/Users/runner/work/1/s/tools/wptrunner/wptrunner/browsers/safari.py", line 212, in stop
2023-07-17T04:27:06.9661240Z     proc.wait(10)
2023-07-17T04:27:06.9662270Z   File "/Users/runner/work/1/s/_venv3/lib/python3.11/site-packages/psutil/__init__.py", line 1270, in wait
2023-07-17T04:27:06.9663330Z     self._exitcode = self._proc.wait(timeout)
2023-07-17T04:27:06.9664630Z                      ^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-17T04:27:06.9665540Z   File "/Users/runner/work/1/s/_venv3/lib/python3.11/site-packages/psutil/_psosx.py", line 346, in wrapper
2023-07-17T04:27:06.9666230Z     return fun(self, *args, **kwargs)
2023-07-17T04:27:06.9666480Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-17T04:27:06.9666870Z   File "/Users/runner/work/1/s/_venv3/lib/python3.11/site-packages/psutil/_psosx.py", line 520, in wait
2023-07-17T04:27:06.9667530Z     return _psposix.wait_pid(self.pid, timeout, self._name)
2023-07-17T04:27:06.9668410Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-17T04:27:06.9668840Z   File "/Users/runner/work/1/s/_venv3/lib/python3.11/site-packages/psutil/_psposix.py", line 132, in wait_pid
2023-07-17T04:27:06.9669470Z     interval = sleep(interval)
2023-07-17T04:27:06.9669720Z                ^^^^^^^^^^^^^^^
2023-07-17T04:27:06.9670110Z   File "/Users/runner/work/1/s/_venv3/lib/python3.11/site-packages/psutil/_psposix.py", line 114, in sleep
2023-07-17T04:27:06.9670780Z     raise TimeoutExpired(timeout, pid=pid, name=proc_name)
2023-07-17T04:27:06.9671440Z psutil.TimeoutExpired: timeout after 10 seconds (pid=12596)
2023-07-17T04:27:06.9671920Z 
2023-07-17T04:27:12.0204460Z 35:04.65 INFO STDERR: Exception in thread 
2023-07-17T04:27:12.0210210Z 35:04.65 INFO STDERR: TestRunnerManager-crashtest-0
2023-07-17T04:27:12.0217160Z 35:04.65 INFO STDERR: :
[exception repeated to stderr]
2023-07-17T04:27:12.8644120Z 35:04.80 SUITE_END
```

**Comment by past** [comment]
Is this now fixed by the merged PR?

**Comment by gsnedders** [comment]
> Is this now fixed by the merged PR?

No, the merged PR merely excluded one failing run from results-analysis, and didn't fix wptrunner.

**Comment by gsnedders** [comment]
c.f. https://github.com/giampaolo/psutil/blob/77e5b7445748d30d22c0e3b2e651414da96a88b4/psutil/_psposix.py#L120-L133

So seemingly `PID is not a child of os.getpid() in which case we keep polling until it's gone`, which follows. For some reason it's not going when it's sent SIGKILL.

**Comment by gsnedders** [comment]
I guess some of the problem is that it's unclear how to recover from this.

We should probably make sure we exit with non-zero, at least?

I did speak to @jgraham a bit about handling errors like this better, and some of the challenge here is simply testing `wptrunner.testrunner` better to ensure we actual do sensible things in cases like this.
