### ISSUE TITLE
Safari stable runs missing since September 13th

### ISSUE THREAD

**Issue by DanielRyanSmith** [web-platform-tests/wpt#48223]
The last run for Safari stable was the 12th. 

https://wpt.fyi/runs?label=master&label=stable&max-count=100&product=chrome&product=firefox&product=safari

Looking at [the invalid runs tab here](https://wpt.fyi/status), I'm seeing some invalid Safari runs on the 16th.

CC @gsnedders

**Comment by gsnedders** [comment]
Retrying the last few runs (i.e., all the daily runs since the 12th) on the 16th failed because it was then rerunning them with the now-released Safari 18.0, thus the invalid runs.

I've hit re-run on the first Azure Pipelines run where everything is running against Safari 18.0 (i.e., from today).

We also got https://github.com/web-platform-tests/wpt/actions/runs/10894890454 yesterday, but it failed to upload results.

**Comment by past** [comment]
https://github.com/web-platform-tests/wpt.fyi/pull/4003 should fix the missing runs from GitHub Actions at least. Daniel, can you schedule another deployment this week?

**Comment by DanielRyanSmith** [comment]
A new version of wpt.fyi has been deployed today. 👍

**Comment by gsnedders** [comment]
@DanielRyanSmith @past Re-running the notify job is still failing in the same way: https://github.com/web-platform-tests/wpt/actions/runs/10925326720/job/30347359745

Not sure if either of you have any insights here?

**Comment by DanielRyanSmith** [comment]
I haven't had a chance to look at this in-depth, but that correlates to [the logic here](https://github.com/web-platform-tests/wpt.fyi/blob/b0de787b9831888d74e9fb650baad46ee6f7de4f/shared/params.go#L53-L65).

**Comment by gsnedders** [comment]
@DanielRyanSmith Sure, but I don't see how we've ended up there at all. Like, we should be on a route that shouldn't ever end up there, far as I can tell?

**Comment by past** [comment]
Looking at the code with the help of a debugger shows that the /api/checks/github-actions route isn't handled by the new handler, but goes through the same handler as the /api/checks/{commit} route.

**Comment by DanielRyanSmith** [comment]
I don't know if anything else has changed, but I can see that we have some [newly ingested aligned runs](https://wpt.fyi/runs?label=master&label=stable&max-count=100&product=chrome&product=firefox&product=safari).

**Comment by gsnedders** [comment]
This is just prodding the Azure Pipelines runs to re-run; nothing is actually solved.

We should maybe spin out the wpt.fyi problems onto an issue on that repo?

**Comment by past** [comment]
Filed https://github.com/web-platform-tests/wpt.fyi/issues/4009

**Comment by past** [comment]
The fix for the missing runs from GitHub Actions was just deployed. We should hopefully see some runs later today.

**Comment by gsnedders** [comment]
So https://github.com/web-platform-tests/wpt/actions/runs/11039052681/job/30670828741 succeeded (which implies that the results receiver got through the uploader and all without giving any error), got 200 back, https://wpt.fyi/status doesn't list any pending github-actions submissions, https://wpt.fyi/runs?max-count=100&from=2024-09-18T00%3A00&product=safari%5Bgithub-actions%5D doesn't have any runs either. There's a bunch of logging, but I don't know where that ends up?

**Comment by past** [comment]
Safari runs are now producing results consistently after the migration to GitHub Actions.
