### ISSUE TITLE
Trickled responses are cacheable

### ISSUE THREAD

**Issue by wpt-issue-mover** [web-platform-tests/wpt#8375]
Originally posted as https://github.com/w3c/wptserve/issues/118 by @gsnedders on 07 Apr 2017, 16:33 UTC:

> With http://web-platform.test:8000/images/blue.png?pipe=trickle(d5) included as an image, Firefox will take 7s (as expected) to load initially; it will thereafter load instantly from cache. This is problematic. Trickled responses *must not* be cacheable.

**Comment by foolip** [comment]
I think this invalid, these are the headers sent with http://web-platform.test:8000/images/blue.png?pipe=trickle(d5) now:
> Content-Type: image/png
> Server: BaseHTTP/0.3 Python/2.7.6
> Date: Tue, 21 Nov 2017 15:13:15 GMT

**Comment by gsnedders** [comment]
With no `Cache-Control` header specifying otherwise, a resource is cacheable. So this still stands.

**Comment by foolip** [comment]
OK, then.

**Comment by jgraham** [comment]
I'm pretty sure this got fixed at some point since there's now code that adds a cache-control  header.

**Comment by irori** [comment]
I saw this still happening in #15075, where Taskcluster ran each test 10 times and all but the first run failed because trickled resources are loaded from cache with no delay.

**Comment by foolip** [comment]
Thanks for reopening this @irori!

I see `Cache-Control: max-age=1000` among the headers sent, so that's clearly no good.
